### ISSUE TITLE
Check collision point index

### ISSUE THREAD

**Issue by HaileyMai** [scleronomic/chompy#1]
https://github.com/scleronomic/chompy/blob/2df3e73e7ffaff834cf971bd9b8dba9dfa4ef8a4/Optimizer/obstacle_collision.py#L141-L147

Here if we want to know the index of the "most dangerous" point in each path, we should use `d_idx = d.argmin(axis=-2) ` before line 145.

**Comment by tenhjo** [comment]
Yes in this case we get the sphere with the largest penetration.
Is this related to maximal iterations for world generation?

**Comment by HaileyMai** [comment]
No, I just wanted to add visualization of the collide point. (not that important)
